[twitch]
oauth = "oauth:abcd"
botname = "yucibot"
channel = "mstiekema"
admin = "mstiekema"
clientId = "clientId"
clientSecret = "clientSecret"
loginCallbackUrl = "http://localhost:9090/auth/twitch/callback"

[apiKeys]
ytApiKey = "somekey"
twitter_consumer_key = "somekey"
twitter_consumer_secret = "somekey"
twitter_access_token_key = "somekey"
twitter_access_token_secret = "somekey"
secretCookieKey = "somekey"

[mysql]
username = "root"
password = "password"
database = "yucibot"
